# Generated by Django 4.2 on 2023-04-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comesFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='typeOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turkish', models.CharField(max_length=200)),
                ('english', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('extraInformation', models.CharField(blank=True, max_length=200, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('etymology', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('original', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.comesfrom')),
                ('structureType', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.typeof')),
            ],
        ),
    ]
