# Generated by Django 4.2 on 2023-04-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_structure_slug_alter_typeof_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comesfrom',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='structure',
            name='original',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='structureType',
        ),
        migrations.AddField(
            model_name='structure',
            name='original',
            field=models.ManyToManyField(blank=True, null=True, to='dictionary.comesfrom'),
        ),
        migrations.AddField(
            model_name='structure',
            name='structureType',
            field=models.ManyToManyField(blank=True, null=True, to='dictionary.typeof'),
        ),
    ]
