# Generated by Django 4.2 on 2023-04-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_comesfrom_slug_remove_structure_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='last_searched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
