# Generated by Django 4.2 on 2023-04-22 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_structure_last_searched_structure_search_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrector', models.CharField(max_length=200)),
                ('corrector_mail', models.EmailField(max_length=254)),
                ('correction', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('toStructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.structure')),
            ],
        ),
    ]
