# Generated by Django 4.2 on 2023-04-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='original',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='structureType',
        ),
        migrations.AddField(
            model_name='structure',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.comesfrom'),
        ),
        migrations.AddField(
            model_name='structure',
            name='structureType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.typeof'),
        ),
    ]
